version: '3.5'

networks:
  reto_3_network:

services:
  laravel:
    build:
      context: '.'
    container_name: laravel
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000    
    ports:
      - 8080:80
    volumes:
      - ./application:/var/www/html
    networks:
      reto_3_network:

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=reto_3
      - MYSQL_USER=reto_3
      - MYSQL_PASSWORD=reto_3
    networks:
      reto_3_network:


